package me.noxxll.adminpanel;
import org.bukkit.*; import org.bukkit.ban.BanList; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
import java.util.*;
public final class PanelManager {
    private final AdminPanel plugin; private final MuteManager mute;
    public PanelManager(AdminPanel p,MuteManager m){plugin=p;mute=m;}
    String color(String s){return ChatColor.translateAlternateColorCodes('&',s);}
    String msg(String k){return color(plugin.getConfig().getString("messages."+k,"&cMessage missing."));}
    ItemStack item(Material m,String n,String... lore){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(color(n));List<String> l=new ArrayList<>();for(String s:lore)l.add(color(s));x.setLore(l);i.setItemMeta(x);}return i;}
    public void openMain(Player p){Inventory i=Bukkit.createInventory(new PanelHolder(PanelType.MAIN,null,0),27,color(plugin.getConfig().getString("settings.panel-title")));
        i.setItem(11,item(Material.PLAYER_HEAD,"&b&lPLAYERS","&7Manage online players"));i.setItem(13,item(Material.BARRIER,"&c&lSERVER","&7Server controls"));i.setItem(15,item(Material.COMPARATOR,"&e&lSETTINGS","&7AdminPanel settings"));p.openInventory(i);}
    public void openPlayers(Player p,int page){List<Player> ps=new ArrayList<>(Bukkit.getOnlinePlayers());ps.sort(Comparator.comparing(Player::getName,String.CASE_INSENSITIVE_ORDER));int max=Math.max(0,(ps.size()-1)/36);page=Math.max(0,Math.min(page,max));
        Inventory i=Bukkit.createInventory(new PanelHolder(PanelType.PLAYERS,null,page),45,color(plugin.getConfig().getString("settings.players-title")));
        for(int n=0;n<36&&page*36+n<ps.size();n++){Player t=ps.get(page*36+n);i.setItem(n,item(Material.PLAYER_HEAD,"&b&l"+t.getName(),mute.isMuted(t.getUniqueId())?"&e[MUTED]":"&a[ONLINE]","&7Click to manage."));}
        i.setItem(40,item(Material.ARROW,"&7← Back"));if(page>0)i.setItem(39,item(Material.SPECTRAL_ARROW,"&bPrevious page"));if(page<max)i.setItem(41,item(Material.SPECTRAL_ARROW,"&bNext page"));p.openInventory(i);}
    public void openPlayer(Player a,Player t){String title=plugin.getConfig().getString("settings.player-title").replace("%player%",t.getName());Inventory i=Bukkit.createInventory(new PanelHolder(PanelType.PLAYER,t.getUniqueId(),0),36,color(title));
        i.setItem(4,item(Material.PLAYER_HEAD,"&b&l"+t.getName(),"&7Health: &f"+Math.round(t.getHealth())+"/20","&7Food: &f"+t.getFoodLevel()+"/20","&7Gamemode: &f"+t.getGameMode(),"&7World: &f"+t.getWorld().getName(),"&7XYZ: &f"+t.getLocation().getBlockX()+" "+t.getLocation().getBlockY()+" "+t.getLocation().getBlockZ()));
        i.setItem(10,item(Material.IRON_SWORD,"&c&lBAN"));i.setItem(11,item(Material.MUSIC_DISC_13,"&e&lMUTE"));i.setItem(12,item(Material.BARRIER,"&c&lKICK"));i.setItem(14,item(Material.ENDER_PEARL,"&b&lTELEPORT"));i.setItem(15,item(Material.ENDER_EYE,"&5&lSPECTATE"));i.setItem(16,item(Material.CHEST,"&6&lINVENTORY"));i.setItem(20,item(Material.LIME_DYE,"&a&lUNMUTE"));i.setItem(31,item(Material.ARROW,"&7← Back"));a.openInventory(i);}
    public void durationMenu(Player a,Player t,boolean ban){PanelType type=ban?PanelType.BAN:PanelType.MUTE;String key=ban?"ban-title":"mute-title";Inventory i=Bukkit.createInventory(new PanelHolder(type,t.getUniqueId(),0),27,color(plugin.getConfig().getString("settings."+key)));i.setItem(10,item(Material.CLOCK,"&e10 Minutes"));i.setItem(11,item(Material.CLOCK,"&e1 Hour"));i.setItem(12,item(Material.CLOCK,"&e1 Day"));i.setItem(14,item(Material.CLOCK,"&e7 Days"));i.setItem(16,item(Material.RED_CONCRETE,"&c&lPERMANENT"));i.setItem(22,item(Material.ARROW,"&7← Back"));a.openInventory(i);}
    public void openInventory(Player a,Player t){Inventory i=Bukkit.createInventory(new PanelHolder(PanelType.INVENTORY,t.getUniqueId(),0),54,color(plugin.getConfig().getString("settings.inventory-title").replace("%player%",t.getName())));for(int n=0;n<36;n++)i.setItem(n,t.getInventory().getItem(n));i.setItem(45,t.getInventory().getHelmet());i.setItem(46,t.getInventory().getChestplate());i.setItem(47,t.getInventory().getLeggings());i.setItem(48,t.getInventory().getBoots());i.setItem(49,t.getInventory().getItemInOffHand());i.setItem(53,item(Material.ARROW,"&7← Back"));a.openInventory(i);}
    public void ban(Player a,Player t,long s){if(!a.hasPermission("adminpanel.ban")){a.sendMessage(msg("no-permission"));return;}String r="Banned by "+a.getName();Date d=s<0?null:new Date(System.currentTimeMillis()+s*1000L);Bukkit.getBanList(BanList.Type.NAME).addBan(t.getName(),r,d,a.getName());t.kickPlayer(color("&cYou have been banned.\n&7Reason: "+r));a.sendMessage(msg("banned").replace("%player%",t.getName()));a.closeInventory();}
    public void mutePlayer(Player a,Player t,long s){if(!a.hasPermission("adminpanel.mute")){a.sendMessage(msg("no-permission"));return;}mute.mute(t.getUniqueId(),s);t.sendMessage(color("&eYou have been muted."));a.sendMessage(msg("muted").replace("%player%",t.getName()));a.closeInventory();}
    public void unmute(Player a,Player t){if(!a.hasPermission("adminpanel.mute")){a.sendMessage(msg("no-permission"));return;}mute.unmute(t.getUniqueId());a.sendMessage(msg("unmuted").replace("%player%",t.getName()));openPlayer(a,t);}
    public void kick(Player a,Player t){if(!a.hasPermission("adminpanel.kick")){a.sendMessage(msg("no-permission"));return;}t.kickPlayer(color("&cKicked by "+a.getName()));a.sendMessage(msg("kicked").replace("%player%",t.getName()));a.closeInventory();}
    public void teleport(Player a,Player t){if(!a.hasPermission("adminpanel.teleport")){a.sendMessage(msg("no-permission"));return;}a.teleport(t.getLocation());a.sendMessage(msg("teleported").replace("%player%",t.getName()));}
    public void spectate(Player a,Player t){if(!a.hasPermission("adminpanel.spectate")){a.sendMessage(msg("no-permission"));return;}a.setGameMode(GameMode.SPECTATOR);a.teleport(t.getLocation());a.sendMessage(msg("spectating").replace("%player%",t.getName()));}
}